<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.schunker.tls</groupId>
  <artifactId>tls-tool</artifactId>
  <version>1.0-SNAPSHOT</version>

  <name>tls-tool</name>
  <!-- FIXME change it to the project's website -->
  <url>http://www.example.com</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.7</maven.compiler.source>
    <maven.compiler.target>1.7</maven.compiler.target>
    <java.version>11</java.version>
    <!--<plugin.prettier.goal>write</plugin.prettier.goal>-->
    <plugin.prettier.goal>check</plugin.prettier.goal>
    <JavaConsoleKit.version>1.0-SNAPSHOT</JavaConsoleKit.version>
  </properties>

  <repositories>
    <repository>
      <id>local-maven-repo</id>
      <url>file:///${project.basedir}/local-maven-repo</url>
    </repository>
  </repositories>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.schunker.java</groupId>
      <artifactId>JavaConsoleKit</artifactId>
      <version>${JavaConsoleKit.version}</version>
    </dependency>
  </dependencies>

  <build>
    <pluginManagement><!-- lock down plugins versions to avoid using Maven defaults (may be moved to parent pom) -->
      <plugins>
        <!-- clean lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#clean_Lifecycle -->
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.1.0</version>
        </plugin>
        <!-- default lifecycle, jar packaging: see https://maven.apache.org/ref/current/maven-core/default-bindings.html#Plugin_bindings_for_jar_packaging -->
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>2.22.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.0.2</version>
          <configuration>
            <archive>
              <manifest>
                <mainClass>com.schunker.tls.App</mainClass>
              </manifest>
            </archive>
          </configuration>
        </plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>2.5.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>2.8.2</version>
        </plugin>
        <!-- site lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#site_Lifecycle -->
        <plugin>
          <artifactId>maven-site-plugin</artifactId>
          <version>3.7.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-project-info-reports-plugin</artifactId>
          <version>3.0.0</version>
        </plugin>
        <plugin>
          <groupId>com.hubspot.maven.plugins</groupId>
          <artifactId>prettier-maven-plugin</artifactId>
          <version>0.10</version>
          <configuration>
            <printWidth>90</printWidth>
            <tabWidth>4</tabWidth>
            <useTabs>true</useTabs>
            <ignoreConfigFile>true</ignoreConfigFile>
            <ignoreEditorConfig>true</ignoreEditorConfig>
            <!-- Use <inputGlobs> to override the default input patterns -->
            <inputGlobs>
              <!-- These are the default patterns, you can omit <inputGlobs> entirely unless you want to override them -->
              <inputGlob>src/main/java/**/*.java</inputGlob>
              <inputGlob>src/test/java/**/*.java</inputGlob>
            </inputGlobs>
          </configuration>
          <executions>
            <execution>
              <phase>validate</phase>
              <goals>
                <goal>${plugin.prettier.goal}</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <!-- not working
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-shade-plugin</artifactId>
          <version>3.5.0</version>
        </plugin>
        -->
      </plugins>
    </pluginManagement>

    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.5.0</version>
        <configuration>
          <!-- put your configurations here -->
          <!--<finalName>${project.artifactId}-${project.version}-shaded</finalName>-->
          <shadedArtifactAttached>true</shadedArtifactAttached>
          <!--
          <transformers>
            <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
              <mainClass>com.schunker.tlsApp</mainClass>
            </transformer>
          </transformers>
          -->
          <artifactSet>
            <includes>
              <include>com.schunker.java:JavaConsoleKit</include>
            </includes>
          </artifactSet>
          <!--
          <filters>
            <filter>
            </filter>
          </filters>
          -->
        </configuration>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <source>8</source>
          <target>8</target>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
